name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: 安装 PowerShell
      uses: milliewalky/setup-pwsh@v1
      with:
        tag: 'latest'

    - name: 运行构建
      shell: pwsh
      run: ./script/build.ps1

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./output/*
